services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 5647382910
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_TCP_PORT: 3306  # Добавлено
    command: ['mysqld', '--bind-address=0.0.0.0']  # Добавлено
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  php: #phpideconfig=serverName phpStorm переменная среды
    build: ../docker
    container_name: php_app
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ../samson-tasks:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    sysctls:
      - net.core.somaxconn=65535
    cap_add:
      - NET_ADMIN
      - NET_RAW  
    dns:
      - 8.8.8.8
      - 1.1.1.1

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
